name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: main
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: main
        run: python -m pytest tests

      - name: Build Docker image
        working-directory: main
        run: docker build -t flask-backend .

      # Optional: Push Docker image to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Push Docker image
      #   run: |
      #     docker tag flask-backend yourdockerhub/flask-backend:latest
      #     docker push yourdockerhub/flask-backend:latest